const activityData = [
  {
    id: 1,

    timestamp: "02/09/2025, 08:00:00 AM",
    actor: "john@gmail.com",
    action: "User Invited",
    severity: "Critical",
    details: "Invited bob.dilipacme.com as Viewer",
    reason: "New team member onboarding",
  },
  {
    id: 2,
    timestamp: "02/09/2025, 08:00:00 AM",
    actor: "john@gmail.com",
    action: "Assets Added",
    severity: "Medium",
    details: "Invited bob.dilipacme.com as Viewer",
    reason: "New team member onboarding",
  },
  {
    id: 3,
    timestamp: "02/09/2025, 08:00:00 AM",
    actor: "john@gmail.com",
    action: "RBAC Modified",
    severity: "Critical",
    details: "Invited bob.dilipacme.com as Viewer",
    reason: "New team member onboarding",
  },
  {
    id: 4,
    timestamp: "02/09/2025, 08:00:00 AM",
    actor: "john@gmail.com",
    action: "Integration Token Rotated",
    severity: "High",
    details: "Invited bob.dilipacme.com as Viewer",
    reason: "New team member onboarding",
  },
  {
    id: 5,
    timestamp: "02/09/2025, 08:00:00 AM",
    actor: "john@gmail.com",
    action: "Whitelist Added",
    severity: "Medium",
    details: "Invited bob.dilipacme.com as Viewer",
    reason: "New team member onboarding",
  },
  {
    id: 6,
    timestamp: "02/09/2025, 08:00:00 AM",
    actor: "john@gmail.com",
    action: "User Invited",
    severity: "Medium",
    details: "Invited bob.dilipacme.com as Viewer",
    reason: "New team member onboarding",
  },
  {
    id: 7,
    timestamp: "02/09/2025, 08:00:00 AM",
    actor: "john@gmail.com",
    action: "RBAC Modified",
    severity: "High",
    details: "Invited bob.dilipacme.com as Viewer",
    reason: "New team member onboarding",
  },
  {
    id: 8,
    timestamp: "02/09/2025, 08:00:00 AM",
    actor: "john@gmail.com",
    action: "Assets Added",
    severity: "Low",
    details: "Invited bob.dilipacme.com as Viewer",
    reason: "New team member onboarding",
  },
  {
    id: 9,
    timestamp: "02/09/2025, 08:00:00 AM",
    actor: "john@gmail.com",
    action: "Whitelist Added",
    severity: "Low",
    details: "Invited bob.dilipacme.com as Viewer",
    reason: "New team member onboarding",
  },
];

export default activityData;
