const scheduledReportsData = [
  {
    id: 1,
    selected: true,
    reportName: "Weekly Executive Summary",
    frequency: "Weekly",
    format: "PDF",
    recipients: "Client Admin, Approver",
    lastSeen: "02/09/2025, 08:00:00 AM",
    status: "Active",
  },
  {
    id: 2,
    selected: false,
    reportName: "Daily Threat Report",
    frequency: "Daily",
    format: "CSV",
    recipients: "All Analysts",
    lastSeen: "02/09/2025, 08:00:00 AM",
    status: "Inactive",
  },
  {
    id: 3,
    selected: false,
    reportName: "Monthly Compliance Report",
    frequency: "Monthly",
    format: "PDF",
    recipients: "Client Admin",
    lastSeen: "02/09/2025, 08:00:00 AM",
    status: "Active",
  },
  {
    id: 4,
    selected: false,
    reportName: "Weekly Executive Summary",
    frequency: "Weekly",
    format: "CSV",
    recipients: "Client Admin, Approver",
    lastSeen: "02/09/2025, 08:00:00 AM",
    status: "Inactive",
  },
  {
    id: 5,
    selected: false,
    reportName: "Daily Threat Report",
    frequency: "Daily",
    format: "CSV",
    recipients: "All Analysts",
    lastSeen: "02/09/2025, 08:00:00 AM",
    status: "Active",
  },
  {
    id: 6,
    selected: false,
    reportName: "Monthly Compliance Report",
    frequency: "Monthly",
    format: "CSV",
    recipients: "Client Admin",
    lastSeen: "02/09/2025, 08:00:00 AM",
    status: "Inactive",
  },
  {
    id: 7,
    selected: false,
    reportName: "Weekly Executive Summary",
    frequency: "Weekly",
    format: "PDF",
    recipients: "Client Admin, Approver",
    lastSeen: "02/09/2025, 08:00:00 AM",
    status: "Active",
  },
  {
    id: 8,
    selected: false,
    reportName: "Daily Threat Report",
    frequency: "Daily",
    format: "CSV",
    recipients: "All Analysts",
    lastSeen: "02/09/2025, 08:00:00 AM",
    status: "Inactive",
  },
  {
    id: 9,
    selected: false,
    reportName: "Monthly Compliance Report",
    frequency: "Monthly",
    format: "PDF",
    recipients: "Client Admin",
    lastSeen: "02/09/2025, 08:00:00 AM",
    status: "Active",
  },
];

export default scheduledReportsData;
